config/routes.rb
Rainforest::Application.routes.draw do

  get "reviews/show"
  get "reviews/new"
  get "reviews/edit"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "users/new"
  get "users/create"

  resources :products do
    resources :reviews, :except => [:index]
  end
  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  root :to => "products#index"
end

app/models/product.rb
class Product < ActiveRecord::Base

	validates :description, :name, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}

  has_many :reviews
  has_many :users, :through => :reviews

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

	belongs_to :user
	belongs_to :product
	validates :comment, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	validates_presence_of :name
	has_many :reviews
	has_many :products, :through => :reviews

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  	end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_filter :ensure_logged_in, :only => [:show]

  def index
    @products = if params[:search]
      Product.where("name ILIKE ?", "%#{params[:search]}%")
    else
      Product.all
    end
    
    @products = @products.order(created_at: :desc).page(params[:page])
    
    respond_to do |format|
      format.html
      format.js
    end
  end
  # def index
  #   @products = Product.all
  # end

  def show
    @product = Product.find(params[:id])
    if current_user
      @review = @product.reviews.build
      end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents, :url)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :load_product
  before_filter :ensure_logged_in, :only => [:edit, :create, :show, :update, :destroy]


  def show
  	@review = Review.find(params[:id])
  end

  def create
  	@review = @product.reviews.build(review_params)
  	@review.user_id = current_user.id

# =	@review = Review.new(
# =>	:comment		=> params[:review][:comment],
# => 	:product_id	=> @product.id,
# => 	:user_id		=> current_user.id
# => )  
   # 	if @review.save
   #    redirect_to products_path, notice: 'Review created successfully'
   #  else
   #    render :action => :show
  	# end
    respond_to do |format|
      if @review.save
        format.html { redirect_to product_path(@product.id), notice: 'Review added.' }
        format.js {} # This will look for app/views/reviews/create.js.erb
      else
        format.html { render "products/show", alert: 'There was an error.' }
        format.js {} # This will look for app/views/reviews/create.js.erb
      end
 	  end
  end

  def new
  end

  def edit
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private
  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_path, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to products_path, :notice => "Signed up!"
  	else
  		render "new"
  	end
  end

	private
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation, :name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>

  <link href='http://fonts.googleapis.com/css?family=Lato:300,700' rel='stylesheet' type='text/css'>

  <link href="//fonts.googleapis.com/css?family=Lato:100italic,100,300italic,300,400italic,400,700italic,700,900italic,900" rel="stylesheet" type="text/css">

  <title>Rainforest</title>

  <style>
  a {color: #58585B;}
  :link {text-decoration:none;}
  a:hover {color: #8FB4C2;}
  </style>
 
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>

<header>

    <div id="logo"> 
      <%=image_tag image_path('rainforest_logo.png') %>
    </div>

    <div id="menu">
      <ul>
        <li>|  <%= link_to 'home', "/products" %></li>
        <li>|  <%= link_to 'log in', "/sessions/new" %></li>
        <li>|  <%= link_to 'sign up', "/users/new" %></li>
        <li>|  <%= link_to 'add a book', "/products/new" %></li>
      </ul>
    </div>

</header>

<div id="container">




  <% if flash[:notice] %>
		<p id="notice"><%= flash[:notice] %></p>
	<% end %>
	<% if flash[:alert] %>
	
  <p id="alert"><%= flash[:alert] %></p>
<% end %>

</div>


<%= yield %>

    <div id="status">
       <% if current_user %>
        <p>Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %></p>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
    </div>



</div>

</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div> 
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
    <div class="field">
    <%= f.label :url %><br />
    <%= f.text_area :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<%= link_to product_path(product.id) do %>
<h2>
	<%= number_to_currency(product.formatted_price) %>
	<%= product.name %>
</h2>
<% end %>

<p><%= truncate(product.description, length: 100) %></p>

app/views/products/_review_errors.html.erb
<% if @review.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

    <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/products/_reviews.html.erb
<% @product.reviews.each do |review| %>
  <% if review.id.present? %>
    <div class="review">
      <p>
        <%= review.comment %>
        <br>
        <% if review.user != nil %>
          <em> by <%= review.user.name %></em>
          Added on: <%= review.created_at %>
        <% end %>
      </p>
    </div>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<div id="container">
<h1>edit product</h1>

<p><%= render 'form' %></p>

<p><%= link_to 'back', products_path %></p>
</div>

app/views/products/index.html.erb
<div id="container">

	<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
		<%= text_field_tag :search, params[:search]  %>
		<%= submit_tag "Search" %>
		<% end %>

<!-- renders a helpful message with numbers of displayed vs. total entries -->

	<p id="products-count"><%= page_entries_info @products %></p>

<div id="products">
	<%= render @products %>
</div>

	<p id="products-pagination"><%= paginate @products %></p>
	<p>  </p>

</div>

app/views/products/index.js.erb
$('#products').append('<%= j render@products) %>');
$('.pagination').replaceWith('<%= j paginate(@products) %>');

// $('products').html("<%= escape_javascript(render @ products) %>");

app/views/products/new.html.erb
<div id="container">
<h1>add a book</h1>



<%= render 'form' %>


</div>

app/views/products/show.html.erb
<div id="container">
<h1>item detail</h1>

<p><%= link_to 'back', products_path %></p>

 <img src="http://flickholdr.com/200/300/sea,sun/1">
 <h2><%= @product.name %></h2>
 <%= @product.url %>
 <p><%= @product.formatted_price %></p>
  <p><%= @product.description %></p>

<% if current_user %>

  <h3>Reviews</h3>

  <p><strong>Reviews for<strong> <%= @product.name %></p>

  <div id="review-list">
    <%= render :partial => "products/reviews" %>
  </div>

  <h4>New Review</h4>

  <%= form_for([@product, @review], remote: true) do |f| %>
  <div id="review-form-errors">
    <%= render :partial => "/products/review_errors" %>
  </div>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
    <% end %>

    <% else %>
      <p>Please <%= link_to "Log In", new_session_path %> to add a review.</p> 
    <% end %>

<%= link_to 'Edit', edit_product_path(@product) %> 


<script type="text/javascript">
  $(function() {
     $("#new_review")
        .on('ajax:beforeSend', function() { 
          $("input[type='submit']") /
            .val('Saving...') 
            .attr('disabled', 'disabled');
        })
        .on('ajax:complete', function() {
          $("input[type='submit']")
            .val('Create Review')
            .removeAttr('disabled');
        });
  });
</script>
 

app/views/reviews/create.js.erb
// $("#review-list").html("<%= escape_javascript(render(:partial => 'products/reviews')) %>");

<% if @review.errors.present? %>
  $("#review-form-errors").html("<%= escape_javascript(render(:partial => '/products/review_errors')) %>");
<% else %>
  $("#review-form-errors").html("");
  $("#review-list").html("<%= escape_javascript(render(:partial => '/products/reviews')) %>");
  $("#new_review")[0].reset();
<% end %>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/users/new.html.erb
<div id="body">
<h1>sign up</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
	<div class="error_messages">
		<h2>Form is invalid</h2>
		<ul>
			<% for message in @user.errors.full_messages %>
			<li><%= message %></li>
<% end %>
	</ul>
  </div>
<% end %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>
</div>

</div>